from __future__ import annotations

from config import DATA_DIR, MAX_TOKENS, MODEL_NAME, TOP_K


APP_NAME = "AI SOC"
DEFAULT_DATA_DIR = DATA_DIR
DEFAULT_MODEL_NAME = MODEL_NAME
DEFAULT_TOP_K = TOP_K
DEFAULT_MAX_TOKENS = MAX_TOKENS